# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['ureg', 'Q', 'Unit']

# %% ../nbs/00_core.ipynb 4
from dataclasses import dataclass

from fastcore.test import test_eq
import pint

# %% ../nbs/00_core.ipynb 5
@dataclass
class Unit:
    """
    Default Units
    """
    
    # SI Unit
    LENGTH = 'meter'
    MASS = 'kilogram'
    TIME = 'second'
    
    # Derived from SI Unit
    VELOCITY = 'meter/second'
    ACCELERATION = 'meter/(second^2)'
    
    FORCE = 'newton'
    ENERGY = 'joule'

# %% ../nbs/00_core.ipynb 6
ureg = pint.UnitRegistry(system='SI')
Q = ureg.Quantity # quantity
