# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_energy.ipynb.

# %% auto 0
__all__ = ['Work', 'Power', 'KineticEnergy', 'PotentialEnergy']

# %% ../nbs/01_energy.ipynb 4
import sympy as smp

from .core import *

# %% ../nbs/01_energy.ipynb 9
class Work:
    def magnitude(
        self,
        initial_position, # initial position of the object
        final_position, # final position of the object
        force, # the force that do work on the object
        path # the path the object taken by the force
    ):
        pass

# %% ../nbs/01_energy.ipynb 11
class Power:
    def magnitude(self, work):
        pass

# %% ../nbs/01_energy.ipynb 13
class KineticEnergy:
    def magnitude(
        self,
        mass, # mass of the object
        velocity # velocity of the object
    ):
        mass = mass.to(Unit.MASS)
        velocity = velocity.to(Unit.VELOCITY)
        
        return (1/2) * mass * velocity

# %% ../nbs/01_energy.ipynb 29
class PotentialEnergy:
    pass
