# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_object.ipynb.

# %% auto 0
__all__ = ['Object', 'Particle', 'RigidBody']

# %% ../nbs/03_object.ipynb 5
class Object:
    pass

# %% ../nbs/03_object.ipynb 6
class Particle(Object):
    pass

# %% ../nbs/03_object.ipynb 7
class RigidBody(Object):
    pass
