# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_position.ipynb.

# %% auto 0
__all__ = ['CoordinateSystem', 'Coordinate', 'Position']

# %% ../nbs/02_position.ipynb 4
import numpy as np
import pandas as pd
from fastcore.test import test_eq

# %% ../nbs/02_position.ipynb 8
class CoordinateSystem:
    pass

# %% ../nbs/02_position.ipynb 10
class Coordinate:
    def __init__(self, x, y, z=None):
        self.x = x
        self.y = y
        self.z = z
    
    def __repr__(self):
        return str(f'({self.x}, {self.y}, {self.z})')

# %% ../nbs/02_position.ipynb 16
class Position:
    def __init__(self):
        self._data = pd.Series([41, 231], dtype=np.float64)
        self._data.index.name = 'Time'
        self._data.name = 'Position'
    
    # def __repr__(self):
    #     return self._data
