# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_universe.ipynb.

# %% auto 0
__all__ = ['Universe', 'BuildUniverse']

# %% ../nbs/00_universe.ipynb 4
import pandas as pd
from .core import *

# %% ../nbs/00_universe.ipynb 6
class Universe:
    def __init__(self):
        #self.initial_energy = initial_energy
        self.is_earth_gravity = False
        #self.is_friction = False

# %% ../nbs/00_universe.ipynb 7
class BuildUniverse(Universe):
    def __init__(self, universe=Universe()):
        self.universe = universe
    
    def setEarthGravity(
        self,
        value: bool # true or false for earth gravity
    ):
        self.universe.is_earth_gravity = value
        return self
    
    # def enableFriction(
    #     self,
    #     value: bool # true of false for friction
    # ):
    #     self.is_friction = value
    #     return self
    
    def build(self):
        return self.universe
