# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_universe.ipynb.

# %% auto 0
__all__ = ['Universe']

# %% ../nbs/00_universe.ipynb 4
import pandas as pd
from .core import *

# %% ../nbs/00_universe.ipynb 6
class Universe:
    def __init__(self, initial_energy):
        self.initial_energy = initial_energy
